/**
 * Pull the three typefaces the UI uses into public/fonts, and write the
 * @font-face rules that point at them.
 *
 * Self-hosted on purpose. Linking Google's CDN would mean two more third-party
 * origins in a CSP that currently has one, and — worse for this app — the
 * whole interface would fall back to system fonts the moment the server is on
 * a LAN with no route out. A media server people run at home should not need
 * the internet to look like itself.
 *
 *   node tools/fetch-fonts.mjs
 *
 * Run once. Re-run only to pick up a newer cut of a face.
 */
import { mkdir, writeFile, readFile } from 'node:fs/promises';
import { existsSync } from 'node:fs';
import path from 'node:path';

const ROOT = path.resolve(import.meta.dirname, '..');
const OUT = path.join(ROOT, 'public', 'fonts');
const CSS = path.join(ROOT, 'public', 'css', 'fonts.css');

/*
 * Google serves a different stylesheet per user agent. Asking as a recent
 * Chrome gets woff2 with unicode-range splits; we only want the latin subset,
 * which is every glyph this interface uses and about a fifth of the bytes.
 */
const UA = 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36';

const FAMILIES = [
  { name: 'Archivo',        slug: 'archivo',  query: 'Archivo:wght@600;700;800;900' },
  { name: 'Hanken Grotesk', slug: 'hanken',   query: 'Hanken+Grotesk:wght@400;500;600;700' },
  { name: 'JetBrains Mono', slug: 'jetbrains', query: 'JetBrains+Mono:wght@400;500;600' }
];

async function get(url, asText = true) {
  const res = await fetch(url, { headers: { 'User-Agent': UA } });
  if (!res.ok) throw new Error(`${res.status} ${res.statusText} for ${url}`);
  return asText ? res.text() : Buffer.from(await res.arrayBuffer());
}

/** Pull one @font-face block apart into the bits we need to rewrite it. */
function parseFaces(css) {
  const faces = [];
  const blocks = css.match(/@font-face\s*{[^}]+}/g) || [];
  for (const block of blocks) {
    const range = /unicode-range:\s*([^;]+);/.exec(block);
    // Latin only. The other subsets are for scripts this UI never renders.
    if (range && !/U\+0000-00FF/.test(range[1])) continue;
    const url = /src:\s*url\(([^)]+)\)/.exec(block);
    const weight = /font-weight:\s*([^;]+);/.exec(block);
    const style = /font-style:\s*([^;]+);/.exec(block);
    if (!url) continue;
    faces.push({
      url: url[1].replace(/['"]/g, ''),
      weight: (weight ? weight[1] : '400').trim(),
      style: (style ? style[1] : 'normal').trim(),
      range: range ? range[1].trim() : null
    });
  }
  return faces;
}

async function main() {
  await mkdir(OUT, { recursive: true });
  const rules = [
    '/* Generated by tools/fetch-fonts.mjs — do not edit by hand.',
    ' * Self-hosted so the interface keeps its typography with no route out.',
    ' */',
    ''
  ];
  let downloaded = 0;

  for (const fam of FAMILIES) {
    const css = await get(`https://fonts.googleapis.com/css2?family=${fam.query}&display=swap`);
    const faces = parseFaces(css);
    if (!faces.length) throw new Error(`no latin faces found for ${fam.name}`);

    /*
     * These are variable fonts, so Google hands back the same file for every
     * weight asked for. Grouping by URL means one download and one @font-face
     * carrying a weight range, instead of four identical copies of Archivo.
     */
    const byUrl = new Map();
    for (const face of faces) {
      const key = face.url;
      if (!byUrl.has(key)) byUrl.set(key, { ...face, weights: [] });
      byUrl.get(key).weights.push(parseInt(face.weight, 10));
    }

    let n = 0;
    for (const face of byUrl.values()) {
      const suffix = byUrl.size > 1 ? `-${n += 1}` : '';
      const file = `${fam.slug}${suffix}${face.style === 'italic' ? '-italic' : ''}.woff2`;
      const dest = path.join(OUT, file);
      if (!existsSync(dest)) {
        await writeFile(dest, await get(face.url, false));
        downloaded += 1;
      }
      const lo = Math.min(...face.weights), hi = Math.max(...face.weights);
      rules.push(
        '@font-face {',
        `  font-family: "${fam.name}";`,
        `  font-style: ${face.style};`,
        `  font-weight: ${lo === hi ? lo : `${lo} ${hi}`};`,
        '  font-display: swap;',
        `  src: url("/fonts/${file}") format("woff2");`,
        face.range ? `  unicode-range: ${face.range};` : null,
        '}',
        ''
      );
    }
    console.log(`${fam.name}: ${faces.length} weight(s) -> ${byUrl.size} file(s)`);
  }

  await writeFile(CSS, rules.filter((line) => line !== null).join('\n'));
  console.log(`\n${downloaded} file(s) written to public/fonts`);
  console.log('wrote public/css/fonts.css');
}

main().catch((err) => {
  console.error('\nCould not fetch the fonts:', err.message);
  console.error('The UI still works — it falls back to the system sans until this succeeds.');
  process.exitCode = 1;
});
